#!/bin/bash

vgavid=`xrandr | grep VGA | awk '{print $1}'`
lvdsvid=`xrandr | grep LVDS | awk '{print $1}'`

whichmode=`zenity --list --radiolist \
--title "Change Display Mode" \
--text "Choose where you want to display your desktop." \
--column="" --column="" --column="Options" \
"" "1" "Just the Laptop's LCD" \
"" "2" "Just the Output Monitor" \
"" "3" "$vgavid Dual Monitor" \
"" "4" "$vgavid Cloned (projector mode)"`

if [ $whichmode -eq 1 ]
then
   xrandr --output $vgavid --off --output $lvdsvid --auto
fi
if [ $whichmode -eq 2 ]
then
   if xrandr -q | grep -q "$vgavid connected"; then
       xrandr --output $lvdsvid --off --output $vgavid --mode 1024x768
   fi
fi
if [ $whichmode -eq 3 ]
then
   if xrandr -q | grep -q "$vgavid connected"; then
       xrandr --output $vgavid --mode 1024x768 --left-of $lvdsvid --output $lvdsvid --mode 1366x768
   fi
fi
if [ $whichmode -eq 4 ]
then
   if xrandr -q | grep -q "$vgavid connected"; then
       xrandr --output $vgavid --mode 1024x768 --pos 0x0 --output $lvdsvid --mode 1366x768 --pos 0x0
   fi
fi
