#!/bin/sh

whichmode=`zenity --list --radiolist \
--title "Change Display Mode" \
--text "Choose where you want to display your desktop." \
--column="" --column="" --column="Options" \
"" "1" "Just the Laptop's LCD" \
"" "2" "Just the Output Monitor" \
"" "3" "VGA1 Dual Monitor" \
"" "4" "VGA1 Cloned (projector mode)"`

if [ $whichmode -eq 1 ]
then
   xrandr --output VGA1 --off --output LVDS1 --auto
fi
if [ $whichmode -eq 2 ]
then
   if xrandr -q | grep -q "VGA1 connected"; then
       xrandr --output LVDS1 --off --output VGA1 --mode 1024x768
   fi
fi
if [ $whichmode -eq 3 ]
then
   if xrandr -q | grep -q "VGA1 connected"; then
       xrandr --output VGA1 --mode 1024x768 --left-of LVDS1 --output LVDS1 --mode 1366x768
   fi
fi
if [ $whichmode -eq 4 ]
then
   if xrandr -q | grep -q "VGA1 connected"; then
       xrandr --output VGA1 --mode 1024x768 --pos 0x0 --output LVDS1 --mode 1366x768 --pos 0x0
   fi
fi
